### ISSUE TITLE
How to get training code?

### ISSUE THREAD

**Issue by oserikov** [Aso-UniMelb/neural-fieldwork-guide#1]
Dear Aso! Dear authors! What a brilliant work! I really loved your paper and wanted to play around with it to see if I can apply it to my languages data. However, I find the training code missing from the repository. Could you , please advice on how to get it? If it's private, may I have a non-distributable copy on my email `srkvoa@gmail.com`?

https://github.com/Aso-UniMelb/neural-fieldwork-guide/blob/dcd9375f17de8f9ac69575bbfb3e66986d37d0a5/guide/fieldwork_guide.sh#L41C14-L41C26

**Comment by aso-mehmudi** [comment]
Dear Oleg, 

Thank you so much for your attention and interest. The training code is not private. We have used neural character-level transformer described in [Wu and Cotterell, 2019](https://arxiv.org/abs/2005.10213). Please copy the **src** folder from [github.com/shijie-wu/neural-transducer/](https://github.com/shijie-wu/neural-transducer/)

If you encounter any issues while running the code, please feel free to contact me.

**Comment by oserikov** [comment]
Thank you @aso-mehmudi !
